apiVersion: v1
kind: Secret
metadata:
  namespace: n8n
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: $(POSTGRES_USER)
  POSTGRES_PASSWORD: $(POSTGRES_PASSWORD)
  POSTGRES_DB: $(POSTGRES_DB)
  POSTGRES_NON_ROOT_USER: $(POSTGRES_NON_ROOT_USER)
  POSTGRES_NON_ROOT_PASSWORD: $(POSTGRES_NON_ROOT_PASSWORD)
